In [1]:
import polars as pl

In [3]:
## Config

path = "C:\\Users\\Arnold\\OneDrive\\Desktop\\CAPSTONE PROJECT\\farming_risk_regions\\data\\interim\\yield_data\\corn_yields_20251021.csv"

In [5]:
yield_data = pl.read_csv(path)

In [6]:
yield_data.head()

shape: (5, 9)
┌──────┬──────┬───────┬────────┬───┬─────────────────────┬─────────────┬────────────┬────────────┐
│ crop ┆ year ┆ state ┆ county ┆ … ┆ area_harvested_unit ┆ yield_value ┆ yield_unit ┆ data_found │
│ ---  ┆ ---  ┆ ---   ┆ ---    ┆   ┆ ---                 ┆ ---         ┆ ---        ┆ ---        │
│ str  ┆ i64  ┆ str   ┆ str    ┆   ┆ str                 ┆ f64         ┆ str        ┆ bool       │
╞══════╪══════╪═══════╪════════╪═══╪═════════════════════╪═════════════╪════════════╪════════════╡
│ CORN ┆ 2014 ┆ IA    ┆ Story  ┆ … ┆ ACRES               ┆ 169.9       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2015 ┆ IA    ┆ Story  ┆ … ┆ ACRES               ┆ 188.0       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2016 ┆ IA    ┆ Story  ┆ … ┆ ACRES               ┆ 211.9       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2017 ┆ IA    ┆ Story  ┆ … ┆ ACRES               ┆ 200.3       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2018 ┆ IA    ┆ Story  ┆ … ┆ ACRES               ┆ 192.3       ┆ BU / ACRE  ┆ true       │
└──────┴──────┴───────┴────────┴───┴─────────────────────┴─────────────┴────────────┴────────────┘

In [7]:
yield_data.tail()

shape: (5, 9)
┌──────┬──────┬───────┬────────┬───┬─────────────────────┬─────────────┬────────────┬────────────┐
│ crop ┆ year ┆ state ┆ county ┆ … ┆ area_harvested_unit ┆ yield_value ┆ yield_unit ┆ data_found │
│ ---  ┆ ---  ┆ ---   ┆ ---    ┆   ┆ ---                 ┆ ---         ┆ ---        ┆ ---        │
│ str  ┆ i64  ┆ str   ┆ str    ┆   ┆ str                 ┆ f64         ┆ str        ┆ bool       │
╞══════╪══════╪═══════╪════════╪═══╪═════════════════════╪═════════════╪════════════╪════════════╡
│ CORN ┆ 2020 ┆ MO    ┆ Saline ┆ … ┆ ACRES               ┆ 195.7       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2021 ┆ MO    ┆ Saline ┆ … ┆ null                ┆ null        ┆ null       ┆ false      │
│ CORN ┆ 2022 ┆ MO    ┆ Saline ┆ … ┆ ACRES               ┆ null        ┆ null       ┆ true       │
│ CORN ┆ 2023 ┆ MO    ┆ Saline ┆ … ┆ ACRES               ┆ 175.7       ┆ BU / ACRE  ┆ true       │
│ CORN ┆ 2024 ┆ MO    ┆ Saline ┆ … ┆ ACRES               ┆ 223.1       ┆ BU / ACRE  ┆ true       │
└──────┴──────┴───────┴────────┴───┴─────────────────────┴─────────────┴────────────┴────────────┘

In [9]:
yield_data.describe()

shape: (9, 10)
┌────────────┬──────┬──────────┬───────┬───┬───────────────┬─────────────┬────────────┬────────────┐
│ statistic  ┆ crop ┆ year     ┆ state ┆ … ┆ area_harveste ┆ yield_value ┆ yield_unit ┆ data_found │
│ ---        ┆ ---  ┆ ---      ┆ ---   ┆   ┆ d_unit        ┆ ---         ┆ ---        ┆ ---        │
│ str        ┆ str  ┆ f64      ┆ str   ┆   ┆ ---           ┆ f64         ┆ str        ┆ f64        │
│            ┆      ┆          ┆       ┆   ┆ str           ┆             ┆            ┆            │
╞════════════╪══════╪══════════╪═══════╪═══╪═══════════════╪═════════════╪════════════╪════════════╡
│ count      ┆ 121  ┆ 121.0    ┆ 121   ┆ … ┆ 105           ┆ 103.0       ┆ 103        ┆ 121.0      │
│ null_count ┆ 0    ┆ 0.0      ┆ 0     ┆ … ┆ 16            ┆ 18.0        ┆ 18         ┆ 0.0        │
│ mean       ┆ null ┆ 2019.0   ┆ null  ┆ … ┆ null          ┆ 199.863107  ┆ null       ┆ 0.867769   │
│ std        ┆ null ┆ 3.175426 ┆ null  ┆ … ┆ null          ┆ 20.207395   ┆ null       ┆ null       │
│ min        ┆ CORN ┆ 2014.0   ┆ IA    ┆ … ┆ ACRES         ┆ 123.3       ┆ BU / ACRE  ┆ 0.0        │
│ 25%        ┆ null ┆ 2016.0   ┆ null  ┆ … ┆ null          ┆ 190.2       ┆ null       ┆ null       │
│ 50%        ┆ null ┆ 2019.0   ┆ null  ┆ … ┆ null          ┆ 201.0       ┆ null       ┆ null       │
│ 75%        ┆ null ┆ 2022.0   ┆ null  ┆ … ┆ null          ┆ 212.8       ┆ null       ┆ null       │
│ max        ┆ CORN ┆ 2024.0   ┆ NE    ┆ … ┆ ACRES         ┆ 246.7       ┆ BU / ACRE  ┆ 1.0        │
└────────────┴──────┴──────────┴───────┴───┴───────────────┴─────────────┴────────────┴────────────┘