In [2]:
import pathlib
import polars as pl
import plotly.express as px
import plotly.graph_objects as go

In [3]:
## Config

INSURANCE_DATA_PATH = pathlib.Path("../data/raw/insurance_data")
OUTPUT_PATH = pathlib.Path("../data/interim/insurance_data/combined_insurance_data.txt")

In [4]:
file_pattern = "*.txt"
order = sorted(INSURANCE_DATA_PATH.glob(file_pattern))
print(order)

[WindowsPath('../data/raw/insurance_data/rma_2014.txt'), WindowsPath('../data/raw/insurance_data/rma_2015.txt'), WindowsPath('../data/raw/insurance_data/rma_2016.txt'), WindowsPath('../data/raw/insurance_data/rma_2017.txt'), WindowsPath('../data/raw/insurance_data/rma_2018.txt'), WindowsPath('../data/raw/insurance_data/rma_2019.txt'), WindowsPath('../data/raw/insurance_data/rma_2020.txt'), WindowsPath('../data/raw/insurance_data/rma_2021.txt'), WindowsPath('../data/raw/insurance_data/rma_2022.txt'), WindowsPath('../data/raw/insurance_data/rma_2023.txt'), WindowsPath('../data/raw/insurance_data/rma_2024.txt'), WindowsPath('../data/raw/insurance_data/rma_2025.txt')]

In [5]:
def combine_files(files, output_path):
    """Combine multiple text files into one output file.
    
    Args:
        files: List of Path objects for input files
        output_path: Path object for output file
    """
    try:
        # Create output directory if it doesn't exist
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with output_path.open("w", encoding="utf-8", newline="\n") as outfile:
            for file in files:
                try:
                    with file.open("r", encoding="utf-8") as src:
                        content = src.read()
                        if content:  # Only write if content is not empty
                            outfile.write(content + "\n")  # Add newline between files
                        print(f"Successfully processed {file.name}")
                except Exception as e:
                    print(f"Error processing {file.name}: {str(e)}")
                    continue
        
        print(f"\nCombined file created at: {output_path}")
        print(f"Output file size: {output_path.stat().st_size} bytes")
        
    except Exception as e:
        print(f"Error creating combined file: {str(e)}")

In [6]:
combine_files(order, OUTPUT_PATH)

Successfully processed rma_2014.txt
Successfully processed rma_2015.txt
Successfully processed rma_2016.txt
Successfully processed rma_2017.txt
Successfully processed rma_2018.txt
Successfully processed rma_2019.txt
Successfully processed rma_2020.txt
Successfully processed rma_2021.txt
Successfully processed rma_2022.txt
Successfully processed rma_2023.txt
Successfully processed rma_2024.txt
Successfully processed rma_2025.txt

Combined file created at: ..\data\interim\insurance_data\combined_insurance_data.txt
Output file size: 313524693 bytes

In [7]:
insurance_data = pl.read_csv(OUTPUT_PATH, 
                             separator="|")

fields = [
    "commodity_year",
    "state_code",
    "state_abbreviation",
    "county_code",
    "county_name",
    "commodity_code",
    "commodity_name",
    "insurance_plan_code",
    "insurance_plan_abbreviation",
    "coverage_category",
    "delivery_type",
    "coverage_level",
    "policies_sold_count",
    "policies_earning_premium_count",
    "policies_indemnified_count",
    "units_earning_premium_count",
    "units_indemnified_count",
    "quantity_type",
    "net_reported_quantity",
    "endorsed_companion_acres",
    "liability_amount",
    "total_premium_amount",
    "subsidy_amount",
    "state_private_subsidy",
    "additional_subsidy",
    "efa_premium_discount",
    "indemnity_amount",
    "loss_ratio"
]


insurance_data.columns = fields

In [8]:
insurance_data.head()

shape: (5, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ additiona ┆ efa_premi ┆ indemnity ┆ loss_rat │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ l_subsidy ┆ um_discou ┆ _amount   ┆ io       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ nt        ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ str       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ i64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 2014      ┆ 2         ┆ AK        ┆ 999       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 2014      ┆ 2         ┆ AK        ┆ 240       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
null_counts = insurance_data.null_count()
null_counts

shape: (1, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ additiona ┆ efa_premi ┆ indemnity ┆ loss_rat │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ l_subsidy ┆ um_discou ┆ _amount   ┆ io       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ nt        ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1708084   ┆ 1708084   ┆ 1708084   ┆ 1708084   ┆ … ┆ 1708084   ┆ 1708084   ┆ 1708084   ┆ 1708116  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
## Removing the null values in the year column
insurance_data = insurance_data.filter(pl.col("commodity_year").is_not_null())

insurance_data.head()

shape: (5, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ additiona ┆ efa_premi ┆ indemnity ┆ loss_rat │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ l_subsidy ┆ um_discou ┆ _amount   ┆ io       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ nt        ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ str       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ i64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2014      ┆ 2         ┆ AK        ┆ 999       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ 2014      ┆ 2         ┆ AK        ┆ 240       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ 2014      ┆ 2         ┆ AK        ┆ 240       ┆ … ┆ 0         ┆ 0         ┆ 2976      ┆ 0.17     │
│ 2014      ┆ 2         ┆ AK        ┆ 240       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ 2014      ┆ 2         ┆ AK        ┆ 240       ┆ … ┆ 0         ┆ 0         ┆ 8494      ┆ 4.49     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:

null_counts = insurance_data.null_count()
null_counts

shape: (1, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ additiona ┆ efa_premi ┆ indemnity ┆ loss_rat │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ l_subsidy ┆ um_discou ┆ _amount   ┆ io       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ nt        ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 32       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
## Checking the datatypes
df_types = pl.DataFrame({"column": insurance_data.columns, "dtype": insurance_data.dtypes})
df_types

shape: (28, 2)
┌───────────────────────┬─────────┐
│ column                ┆ dtype   │
│ ---                   ┆ ---     │
│ str                   ┆ object  │
╞═══════════════════════╪═════════╡
│ commodity_year        ┆ Int64   │
│ state_code            ┆ Int64   │
│ state_abbreviation    ┆ String  │
│ county_code           ┆ Int64   │
│ county_name           ┆ String  │
│ …                     ┆ …       │
│ state_private_subsidy ┆ Int64   │
│ additional_subsidy    ┆ Int64   │
│ efa_premium_discount  ┆ Int64   │
│ indemnity_amount      ┆ Int64   │
│ loss_ratio            ┆ Float64 │
└───────────────────────┴─────────┘

In [13]:
## Checking for state counts

state_counts = insurance_data["state_abbreviation"].value_counts().sort("count", descending=True)
state_counts

shape: (50, 2)
┌────────────────────┬────────┐
│ state_abbreviation ┆ count  │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│ TX                 ┆ 148624 │
│ KS                 ┆ 107008 │
│ ND                 ┆ 94532  │
│ MN                 ┆ 87064  │
│ IL                 ┆ 81497  │
│ …                  ┆ …      │
│ NV                 ┆ 1149   │
│ HI                 ┆ 602    │
│ NH                 ┆ 597    │
│ RI                 ┆ 339    │
│ AK                 ┆ 150    │
└────────────────────┴────────┘

In [14]:

fig = px.bar(state_counts.to_pandas(),
             x="state_abbreviation",
             y="count",
             title="Number of Insurance Policies by State",
             labels={"state_abbreviation": "State", "count": "Number of Policies"})
fig.show()

In [15]:
## Checking for county counts

county_counts = insurance_data["county_name"].value_counts().sort("count", descending=True)
county_counts

shape: (1_739, 2)
┌────────────────────────────────┬───────┐
│ county_name                    ┆ count │
│ ---                            ┆ ---   │
│ str                            ┆ u32   │
╞════════════════════════════════╪═══════╡
│ Washington                     ┆ 14376 │
│ Jackson                        ┆ 12565 │
│ Franklin                       ┆ 12034 │
│ Grant                          ┆ 11444 │
│ Jefferson                      ┆ 11116 │
│ …                              ┆ …     │
│ Coweta                         ┆ 2     │
│ Hinsdale                       ┆ 2     │
│ Towns                          ┆ 2     │
│ Bienville                      ┆ 2     │
│ Pinellas                       ┆ 1     │
└────────────────────────────────┴───────┘

In [16]:
## Getting the top 20 counties with the highest number of insurance policies
top_20_counties = county_counts.head(20)
top_20_counties

shape: (20, 2)
┌────────────────────────────────┬───────┐
│ county_name                    ┆ count │
│ ---                            ┆ ---   │
│ str                            ┆ u32   │
╞════════════════════════════════╪═══════╡
│ Washington                     ┆ 14376 │
│ Jackson                        ┆ 12565 │
│ Franklin                       ┆ 12034 │
│ Grant                          ┆ 11444 │
│ Jefferson                      ┆ 11116 │
│ …                              ┆ …     │
│ Marion                         ┆ 7376  │
│ Clark                          ┆ 6894  │
│ Polk                           ┆ 6820  │
│ Brown                          ┆ 6748  │
│ Calhoun                        ┆ 6705  │
└────────────────────────────────┴───────┘

In [17]:
## combining the county name and state abbreviation for better visualization

insurance_data = insurance_data.with_columns(
    (pl.col("county_name").str.strip_chars() + "," + pl.col("state_abbreviation").str.strip_chars()).alias("county_state")
)
insurance_data.tail()

shape: (5, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ efa_premi ┆ indemnity ┆ loss_rati ┆ county_s │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ um_discou ┆ _amount   ┆ o         ┆ tate     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ nt        ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ str       ┆ i64       ┆   ┆ ---       ┆ i64       ┆ f64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 5350      ┆ 0.03      ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 3508      ┆ 5.65      ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:

## Plotting the top 20 counties with the highest number of insurance policies
top_20_counties = insurance_data["county_state"].value_counts().sort("count", descending=True).head(20)
fig = px.bar(top_20_counties.to_pandas(), x="county_state", y="count", title="Top 20 Counties by Insurance Policies",
             labels={"county_state": "County, State", "count": "Number of Policies"})
fig.show()

In [19]:
## Years with most insurance policies
year_counts = insurance_data["commodity_year"].value_counts().sort("count", descending=True)
year_counts

shape: (12, 2)
┌────────────────┬────────┐
│ commodity_year ┆ count  │
│ ---            ┆ ---    │
│ i64            ┆ u32    │
╞════════════════╪════════╡
│ 2025           ┆ 155703 │
│ 2023           ┆ 153022 │
│ 2024           ┆ 152401 │
│ 2022           ┆ 149930 │
│ 2021           ┆ 147893 │
│ …              ┆ …      │
│ 2018           ┆ 135367 │
│ 2015           ┆ 134391 │
│ 2016           ┆ 134258 │
│ 2017           ┆ 133865 │
│ 2014           ┆ 129601 │
└────────────────┴────────┘

In [20]:
## Visualizing the number of insurance policies by year
fig = px.bar(year_counts, x="commodity_year", y="count",
             title="Number of Insurance Policies by Year",
             labels={"commodity_year": "Year", "count": "Number of Policies"})
fig.show()

In [21]:
## Checking the indemnity amounts by state
state_indemnity = insurance_data.group_by("state_abbreviation").agg(
    pl.sum("indemnity_amount").alias("total_indemnity")
).sort("total_indemnity", descending=True)
state_indemnity

shape: (50, 2)
┌────────────────────┬─────────────────┐
│ state_abbreviation ┆ total_indemnity │
│ ---                ┆ ---             │
│ str                ┆ i64             │
╞════════════════════╪═════════════════╡
│ TX                 ┆ 19646193584     │
│ ND                 ┆ 8666533019      │
│ KS                 ┆ 8019000015      │
│ CA                 ┆ 7506577626      │
│ SD                 ┆ 6145035037      │
│ …                  ┆ …               │
│ HI                 ┆ 30418914        │
│ WV                 ┆ 29664910        │
│ NH                 ┆ 5630483         │
│ RI                 ┆ 2051998         │
│ AK                 ┆ 693845          │
└────────────────────┴─────────────────┘

In [22]:
## Visualizing the number of insurance loss by state

fig = px.bar(state_indemnity.to_pandas(), x="state_abbreviation", y="total_indemnity",
             title="Total Indemnity Amount by State",
             labels={"state_abbreviation": "State", "total_indemnity": "Total Indemnity"})
fig.show()

In [23]:
## Checking indemnity amounts by counties
county_indemnity = insurance_data.group_by("county_state").agg(
    pl.sum("indemnity_amount").alias("total_indemnity")
).sort("total_indemnity", descending=True)  

## Getting the top 20 counties with the highest indemnity amounts
county_indemnity = county_indemnity.head(20)
county_indemnity

shape: (20, 2)
┌──────────────┬─────────────────┐
│ county_state ┆ total_indemnity │
│ ---          ┆ ---             │
│ str          ┆ i64             │
╞══════════════╪═════════════════╡
│ Fresno,CA    ┆ 1244215026      │
│ Gaines,TX    ┆ 996124384       │
│ Kern,CA      ┆ 885335197       │
│ Dawson,TX    ┆ 636158531       │
│ Terry,TX     ┆ 631724066       │
│ …            ┆ …               │
│ Jackson,OK   ┆ 420636544       │
│ Kings,CA     ┆ 411983135       │
│ Cochran,TX   ┆ 409998546       │
│ Castro,TX    ┆ 409529913       │
│ Yoakum,TX    ┆ 402119966       │
└──────────────┴─────────────────┘

In [24]:
## Visualizing the indemnity amounts by counties

fig = px.bar(county_indemnity.to_pandas(), x="county_state", y="total_indemnity",
             title="Total Indemnity Amount by County",
             labels={"county_state": "County", "total_indemnity": "Total Indemnity"})

fig.show()

In [25]:
## Checking counties with highest loss ratios
county_loss_ratio = insurance_data.group_by("county_state").agg(
    pl.mean("loss_ratio").alias("loss_ratio")
).sort("loss_ratio", descending=True)
county_loss_ratio

shape: (2_995, 2)
┌───────────────────────┬────────────┐
│ county_state          ┆ loss_ratio │
│ ---                   ┆ ---        │
│ str                   ┆ f64        │
╞═══════════════════════╪════════════╡
│ Maui,HI               ┆ 3.567925   │
│ All Other Counties,HI ┆ 3.387216   │
│ Juab,UT               ┆ 3.109767   │
│ El Dorado,CA          ┆ 2.870709   │
│ San Mateo,CA          ┆ 2.799737   │
│ …                     ┆ …          │
│ Baldwin,GA            ┆ 0.0        │
│ Macon,NC              ┆ 0.0        │
│ Wayne,WV              ┆ 0.0        │
│ Honolulu,HI           ┆ 0.0        │
│ All Other Counties,SD ┆ 0.0        │
└───────────────────────┴────────────┘

In [26]:
## Visualizing the loss ratios by counties

fig = px.bar(county_loss_ratio.head(20).to_pandas(), x="county_state", y="loss_ratio",
             title="Top 20 Counties by Average Loss Ratio",
             labels={"county_state": "County, State", "loss_ratio": "Average Loss Ratio"})
fig.show()

In [27]:
fig = px.choropleth(state_indemnity.to_pandas(), 
                    locations='state_abbreviation', 
                    locationmode='USA-states', 
                    color='total_indemnity',
                    scope='usa',
                    title='Total Indemnity Amount by State',
                    labels={'total_indemnity': 'Total Indemnity'})
fig.show()

In [35]:
fig = go.Figure(data=go.Choropleth(
    locations=state_counts['state_abbreviation'],
    z=state_counts['count'],
    locationmode='USA-states',
    colorscale='Blues',
    colorbar_title='Number of Policies'
))

fig.update_layout(
    title_text='Number of Insurance Policies by State',
    geo_scope='usa'
)

fig.show()

In [30]:
state_loss_ratio = insurance_data.group_by("state_abbreviation").agg(
    pl.mean("loss_ratio").alias("avg_loss_ratio")
).sort("avg_loss_ratio", descending=True)

fig = px.choropleth(state_loss_ratio.to_pandas(), 
                    locations='state_abbreviation', 
                    locationmode='USA-states', 
                    color='avg_loss_ratio',
                    scope='usa',
                    title='Average Loss Ratio by State',
                    labels={'avg_loss_ratio': 'Average Loss Ratio'})
fig.show()

In [31]:
commodity_counts = insurance_data["commodity_name"].value_counts().sort("count", descending=True)
top_20_commodities = commodity_counts.head(20)
fig = px.bar(top_20_commodities.to_pandas(), x="commodity_name", y="count", title="Top 20 Most Insured Crops",
             labels={"commodity_name": "Crop", "count": "Number of Policies"})
fig.show()

In [34]:
commodity_indemnity = insurance_data.group_by("commodity_name").agg(
    pl.sum("indemnity_amount").alias("total_indemnity")
).sort("total_indemnity", descending=True)

top_20_commodity_indemnity = commodity_indemnity.head(20)

fig = px.bar(top_20_commodity_indemnity.to_pandas(), x="commodity_name", y="total_indemnity", title="Top 20 Commodities by Total Indemnity",
             labels={"commodity_name": "Commodity", "total_indemnity": "Total Indemnity"})
fig.show()